// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: foxglove/Quaternion.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Generated by https://github.com/foxglove/schemas

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A [quaternion](https://eater.net/quaternions) representing a rotation in 3D space
struct Foxglove_Quaternion {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// x value
  var x: Double = 0

  /// y value
  var y: Double = 0

  /// z value
  var z: Double = 0

  /// w value
  var w: Double = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
  extension Foxglove_Quaternion: @unchecked Sendable {}
#endif // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "foxglove"

extension Foxglove_Quaternion: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
  SwiftProtobuf._ProtoNameProviding
{
  static let protoMessageName: String = _protobuf_package + ".Quaternion"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "x"),
    2: .same(proto: "y"),
    3: .same(proto: "z"),
    4: .same(proto: "w"),
  ]

  mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try decoder.decodeSingularDoubleField(value: &x)
      case 2: try decoder.decodeSingularDoubleField(value: &y)
      case 3: try decoder.decodeSingularDoubleField(value: &z)
      case 4: try decoder.decodeSingularDoubleField(value: &w)
      default: break
      }
    }
  }

  func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
    if x != 0 {
      try visitor.visitSingularDoubleField(value: x, fieldNumber: 1)
    }
    if y != 0 {
      try visitor.visitSingularDoubleField(value: y, fieldNumber: 2)
    }
    if z != 0 {
      try visitor.visitSingularDoubleField(value: z, fieldNumber: 3)
    }
    if w != 0 {
      try visitor.visitSingularDoubleField(value: w, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func == (lhs: Foxglove_Quaternion, rhs: Foxglove_Quaternion) -> Bool {
    if lhs.x != rhs.x { return false }
    if lhs.y != rhs.y { return false }
    if lhs.z != rhs.z { return false }
    if lhs.w != rhs.w { return false }
    if lhs.unknownFields != rhs.unknownFields { return false }
    return true
  }
}
