// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: foxglove/TextPrimitive.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Generated by https://github.com/foxglove/schemas

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A primitive representing a text label
struct Foxglove_TextPrimitive {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Position of the center of the text box and orientation of the text. Identity orientation means the text is
  /// oriented in the xy-plane and flows from -x to +x.
  var pose: Foxglove_Pose {
    get { _pose ?? Foxglove_Pose() }
    set { _pose = newValue }
  }

  /// Returns true if `pose` has been explicitly set.
  var hasPose: Bool { _pose != nil }
  /// Clears the value of `pose`. Subsequent reads from it will return its default value.
  mutating func clearPose() { _pose = nil }

  /// Whether the text should respect `pose.orientation` (false) or always face the camera (true)
  var billboard: Bool = false

  /// Font size (height of one line of text)
  var fontSize: Double = 0

  /// Indicates whether `font_size` is a fixed size in screen pixels (true), or specified in world coordinates and
  /// scales with distance from the camera (false)
  var scaleInvariant: Bool = false

  /// Color of the text
  var color: Foxglove_Color {
    get { _color ?? Foxglove_Color() }
    set { _color = newValue }
  }

  /// Returns true if `color` has been explicitly set.
  var hasColor: Bool { _color != nil }
  /// Clears the value of `color`. Subsequent reads from it will return its default value.
  mutating func clearColor() { _color = nil }

  /// Text
  var text: String = .init()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  private var _pose: Foxglove_Pose?
  private var _color: Foxglove_Color?
}

#if swift(>=5.5) && canImport(_Concurrency)
  extension Foxglove_TextPrimitive: @unchecked Sendable {}
#endif // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "foxglove"

extension Foxglove_TextPrimitive: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
  SwiftProtobuf._ProtoNameProviding
{
  static let protoMessageName: String = _protobuf_package + ".TextPrimitive"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "pose"),
    2: .same(proto: "billboard"),
    3: .standard(proto: "font_size"),
    4: .standard(proto: "scale_invariant"),
    5: .same(proto: "color"),
    6: .same(proto: "text"),
  ]

  mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &_pose)
      case 2: try decoder.decodeSingularBoolField(value: &billboard)
      case 3: try decoder.decodeSingularDoubleField(value: &fontSize)
      case 4: try decoder.decodeSingularBoolField(value: &scaleInvariant)
      case 5: try decoder.decodeSingularMessageField(value: &_color)
      case 6: try decoder.decodeSingularStringField(value: &text)
      default: break
      }
    }
  }

  func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if let v = _pose {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if billboard != false {
      try visitor.visitSingularBoolField(value: billboard, fieldNumber: 2)
    }
    if fontSize != 0 {
      try visitor.visitSingularDoubleField(value: fontSize, fieldNumber: 3)
    }
    if scaleInvariant != false {
      try visitor.visitSingularBoolField(value: scaleInvariant, fieldNumber: 4)
    }
    try { if let v = self._color {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !text.isEmpty {
      try visitor.visitSingularStringField(value: text, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func == (lhs: Foxglove_TextPrimitive, rhs: Foxglove_TextPrimitive) -> Bool {
    if lhs._pose != rhs._pose { return false }
    if lhs.billboard != rhs.billboard { return false }
    if lhs.fontSize != rhs.fontSize { return false }
    if lhs.scaleInvariant != rhs.scaleInvariant { return false }
    if lhs._color != rhs._color { return false }
    if lhs.text != rhs.text { return false }
    if lhs.unknownFields != rhs.unknownFields { return false }
    return true
  }
}
